### ISSUE TITLE
`No module named 'bbb'` (easyform 2.1.1, collective.recaptcha 2.1.0 on Plone 5.2, Python 3.7)

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.easyform#198]
When trying to use easyform with collective.recaptcha 2.1.0. On `bin/instance fg`:
```
Traceback (most recent call last):
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 867, in finish
    args = toargs(context, *self.argdata)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 1686, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/fields.py", line 268, in fromUnicode
    v = vt.fromUnicode(s)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/fields.py", line 171, in fromUnicode
    value = self.context.resolve(name)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 225, in resolve
    __import__(mname)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/collective.recaptcha-2.1.0-py3.7.egg/collective/recaptcha/view.py", line 8, in <module>
    from collective.recaptcha.settings import getRecaptchaSettings
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/collective.recaptcha-2.1.0-py3.7.egg/collective/recaptcha/settings.py", line 2, in <module>
    from bbb import getSite
ModuleNotFoundError: No module named 'bbb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/zinstance/parts/instance/bin/interpreter", line 277, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/Zope2/Startup/serve.py", line 252, in <module>
    sys.exit(main() or 0)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/Zope2/Startup/serve.py", line 248, in main
    return command.run()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/Zope2/Startup/serve.py", line 189, in run
    global_conf=vars)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/Zope2/Startup/serve.py", line 217, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/PasteDeploy-2.0.1-py3.7.egg/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/PasteDeploy-2.0.1-py3.7.egg/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/PasteDeploy-2.0.1-py3.7.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/PasteDeploy-2.0.1-py3.7.egg/paste/deploy/loadwsgi.py", line 209, in invoke
    app = context.app_context.create()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/PasteDeploy-2.0.1-py3.7.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/PasteDeploy-2.0.1-py3.7.egg/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/PasteDeploy-2.0.1-py3.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/Zope2/Startup/run.py", line 71, in make_wsgi_app
    starter.prepare()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/Zope2/Startup/starter.py", line 41, in prepare
    self.startZope()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/Zope2/Startup/starter.py", line 98, in startZope
    Zope2.startup_wsgi()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/Zope2/__init__.py", line 50, in startup_wsgi
    _startup()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/Zope2/App/startup.py", line 143, in startup
    load_zcml()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/Zope2/App/startup.py", line 58, in load_zcml
    load_site()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/Zope2/App/zcml.py", line 45, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 657, in file
    include(context, name, package)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/private/tmp/python-20190709-71298-1cfqdlu/Python-3.7.4/Modules/pyexpat.c", line 471, in EndElement
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 868, in finish
    actions = self.handler(context, **args)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/Zope-4.1.1-py3.7.egg/OFS/metaconfigure.py", line 47, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/private/tmp/python-20190709-71298-1cfqdlu/Python-3.7.4/Modules/pyexpat.c", line 471, in EndElement
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 868, in finish
    actions = self.handler(context, **args)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/z3c.autoinclude-0.3.9-py3.7.egg/z3c/autoinclude/zcml.py", line 104, in includePluginsDirective
    includeZCMLGroup(_context, info, filename)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/z3c.autoinclude-0.3.9-py3.7.egg/z3c/autoinclude/zcml.py", line 30, in includeZCMLGroup
    include(_context, filename, includable_package)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/private/tmp/python-20190709-71298-1cfqdlu/Python-3.7.4/Modules/pyexpat.c", line 471, in EndElement
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 235, in _handle_exception
    reraise(exc, None, sys.exc_info()[2])
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/_compat.py", line 30, in reraise
    raise value.with_traceback(tb)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 867, in finish
    args = toargs(context, *self.argdata)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 1686, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/fields.py", line 268, in fromUnicode
    v = vt.fromUnicode(s)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/fields.py", line 171, in fromUnicode
    value = self.context.resolve(name)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/zope.configuration-4.3.1-py3.7.egg/zope/configuration/config.py", line 225, in resolve
    __import__(mname)
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/collective.recaptcha-2.1.0-py3.7.egg/collective/recaptcha/view.py", line 8, in <module>
    from collective.recaptcha.settings import getRecaptchaSettings
  File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/collective.recaptcha-2.1.0-py3.7.egg/collective/recaptcha/settings.py", line 2, in <module>
    from bbb import getSite
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/collective.recaptcha-2.1.0-py3.7.egg/collective/recaptcha/configure.zcml", line 7.2-8.37
    File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/zinstance/parts/instance/etc/site.zcml", line 16.2-16.23
    File "/Users/kimnguyen/PloneBuilds/Plone-5.2.0/buildout-cache/eggs/Products.CMFPlone-5.2.0-py3.7.egg/Products/CMFPlone/configure.zcml", line 110.2-114.8
    ModuleNotFoundError: No module named 'bbb'
```

**Comment by tkimnguyen** [comment]
Never mind... collective.recaptcha is not needed
