### ISSUE TITLE
 _pickle.PicklingError Can't pickle <class 'z3c.form.interfaces.NOT_CHANGED'>: it's not the same object as z3c.form.interfaces.NOT_CHANGED

### ISSUE THREAD

**Issue by zopyx** [collective/collective.easyform#207]
`attachment.rst` test fails with current master.

```

----------------------------------------------------------------------
File "/home/ajung/src/collective.easyform/src/collective/easyform/tests/attachment.rst", line 203, in attachment.rst
Failed example:
    browser.getControl("Apply changes").click()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest attachment.rst[105]>", line 1, in <module>
        browser.getControl("Apply changes").click()
      File "/home/ajung/.buildout/eggs/zope.testbrowser-5.3.3-py3.7.egg/zope/testbrowser/browser.py", line 775, in click
        self.browser._clickSubmit(self._form, self._control)
      File "/home/ajung/.buildout/eggs/zope.testbrowser-5.3.3-py3.7.egg/zope/testbrowser/browser.py", line 271, in _clickSubmit
        self._processRequest(url, make_request)
      File "/home/ajung/.buildout/eggs/zope.testbrowser-5.3.3-py3.7.egg/zope/testbrowser/browser.py", line 276, in _processRequest
        resp = make_request(reqargs)
      File "/home/ajung/.buildout/eggs/zope.testbrowser-5.3.3-py3.7.egg/zope/testbrowser/browser.py", line 266, in make_request
        form, control.name, index, coord=coord, **args)
      File "/home/ajung/.buildout/eggs/zope.testbrowser-5.3.3-py3.7.egg/zope/testbrowser/browser.py", line 310, in _submit
        params=fields, **args)
      File "/home/ajung/.buildout/eggs/WebTest-2.0.33-py3.7.egg/webtest/response.py", line 300, in goto
        return method(href, **args)
      File "/home/ajung/.buildout/eggs/WebTest-2.0.33-py3.7.egg/webtest/app.py", line 382, in post
        content_type=content_type)
      File "/home/ajung/.buildout/eggs/WebTest-2.0.33-py3.7.egg/webtest/app.py", line 758, in _gen_request
        expect_errors=expect_errors)
      File "/home/ajung/.buildout/eggs/zope.testbrowser-5.3.3-py3.7.egg/zope/testbrowser/browser.py", line 95, in do_request
        expect_errors)
      File "/home/ajung/.buildout/eggs/WebTest-2.0.33-py3.7.egg/webtest/app.py", line 628, in do_request
        res = req.get_response(app, catch_exc_info=True)
      File "/home/ajung/.buildout/eggs/WebOb-1.8.5-py3.7.egg/webob/request.py", line 1310, in send
        application, catch_exc_info=True)
      File "/home/ajung/.buildout/eggs/WebOb-1.8.5-py3.7.egg/webob/request.py", line 1278, in call_application
        app_iter = application(self.environ, start_response)
      File "/home/ajung/.buildout/eggs/WebTest-2.0.33-py3.7.egg/webtest/lint.py", line 201, in lint_app
        iterator = application(environ, start_response_wrapper)
      File "/home/ajung/.buildout/eggs/plone.testing-7.0.3-py3.7.egg/plone/testing/_z2_testbrowser.py", line 38, in wrapped_func
        return func(*args, **kw)
      File "/home/ajung/.buildout/eggs/plone.testing-7.0.3-py3.7.egg/plone/testing/_z2_testbrowser.py", line 65, in __call__
        wsgi_result = publish(environ, start_response)
      File "/home/ajung/.buildout/eggs/Zope-4.1.3-py3.7.egg/ZPublisher/WSGIPublisher.py", line 343, in publish_module
        environ['REMOTE_USER'] = user.getUserName()
      File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
        next(self.gen)
      File "/home/ajung/.buildout/eggs/Zope-4.1.3-py3.7.egg/ZPublisher/WSGIPublisher.py", line 178, in transaction_pubevents
        reraise(*exc_info)
      File "/home/ajung/.buildout/eggs/six-1.12.0-py3.7.egg/six.py", line 693, in reraise
        raise value
      File "/home/ajung/.buildout/eggs/Zope-4.1.3-py3.7.egg/ZPublisher/WSGIPublisher.py", line 162, in transaction_pubevents
        tm.commit()
      File "/home/ajung/.buildout/eggs/transaction-2.4.0-py3.7.egg/transaction/_manager.py", line 252, in commit
        return self.manager.commit()
      File "/home/ajung/.buildout/eggs/transaction-2.4.0-py3.7.egg/transaction/_manager.py", line 131, in commit
        return self.get().commit()
      File "/home/ajung/.buildout/eggs/transaction-2.4.0-py3.7.egg/transaction/_transaction.py", line 311, in commit
        reraise(t, v, tb)
      File "/home/ajung/.buildout/eggs/transaction-2.4.0-py3.7.egg/transaction/_compat.py", line 50, in reraise
        raise value
      File "/home/ajung/.buildout/eggs/transaction-2.4.0-py3.7.egg/transaction/_transaction.py", line 302, in commit
        self._commitResources()
      File "/home/ajung/.buildout/eggs/transaction-2.4.0-py3.7.egg/transaction/_transaction.py", line 447, in _commitResources
        reraise(t, v, tb)
      File "/home/ajung/.buildout/eggs/transaction-2.4.0-py3.7.egg/transaction/_compat.py", line 50, in reraise
        raise value
      File "/home/ajung/.buildout/eggs/transaction-2.4.0-py3.7.egg/transaction/_transaction.py", line 421, in _commitResources
        rm.commit(self)
      File "/home/ajung/.buildout/eggs/ZODB-5.5.1-py3.7.egg/ZODB/Connection.py", line 497, in commit
        self._commit(transaction)
      File "/home/ajung/.buildout/eggs/ZODB-5.5.1-py3.7.egg/ZODB/Connection.py", line 546, in _commit
        self._store_objects(ObjectWriter(obj), transaction)
      File "/home/ajung/.buildout/eggs/ZODB-5.5.1-py3.7.egg/ZODB/Connection.py", line 578, in _store_objects
        p = writer.serialize(obj)  # This calls __getstate__ of obj
      File "/home/ajung/.buildout/eggs/ZODB-5.5.1-py3.7.egg/ZODB/serialize.py", line 430, in serialize
        return self._dump(meta, obj.__getstate__())
      File "/home/ajung/.buildout/eggs/ZODB-5.5.1-py3.7.egg/ZODB/serialize.py", line 439, in _dump
        self._p.dump(state)
    _pickle.PicklingError: Can't pickle <class 'z3c.form.interfaces.NOT_CHANGED'>: it's not the same object as z3c.form.interfaces.NOT_CHANGED

```

**Comment by adrianschulz** [comment]
I get the same error message with the following steps.

1. Add a field with field type _Image_ to your form.
2. Go to the form (from user-view) and select a non-image file for this field.
3. Click submit.
4. Select _Keep existing image_.
5. Submit again.

**Comment by parruc** [comment]
I'm having the exact same error using File field. Always when re-submitting the form trying to "keep existing file"
